server:
  port: 8080  # Port where your Spring Boot app will run

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nishankbruno23@gmail.com
    password:
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable:true
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:mvp_db}
    username: ${POSTGRES_USER:mvp_user}
    password: ${POSTGRES_PASSWORD:mvp_password}

  jpa:
    hibernate:
      ddl-auto: update  # We’ll use Flyway migrations, so don’t let Hibernate auto-create tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration  # Where Flyway looks for migration files
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always  # So /actuator/health shows DB details in dev
